/**
 * Datos estáticos del seed NekoFix (demo profesional).
 * Ampliar: añadir filas a SEED_BRANDS, SEED_CATEGORIES, SEED_PHONE_MODELS o SEED_PRODUCTS.
 */
import {
  InventoryMovementType,
  ProductCondition,
  ProductType,
  UserRole,
} from '@prisma/client';

export const SEED_MARKER = '[seed]';

export type SeedProductDef = {
  slug: string;
  sku: string;
  name: string;
  description: string;
  brandSlug: string;
  categorySlug: string;
  modelSlug?: string;
  type: ProductType;
  condition: ProductCondition;
  price: string;
  comparePrice?: string;
  stock: number;
  minStock: number;
  storage?: string;
  color?: string;
  batteryHealth?: number;
  grade?: string;
  isFeatured: boolean;
  seoTitle: string;
  seoDescription: string;
  imageCount: 2 | 3 | 4;
};

export type SeedMovementDef = {
  productSlug: string;
  type: InventoryMovementType;
  quantity: number;
  notes: string;
};

export type SeedLeadDef = {
  id: string;
  phone: string;
  daysAgo: number;
  hoursOffset?: number;
  items: { slug: string; qty: number; unitPrice: string }[];
};

/** IDs fijos para leads idempotentes. */
export const SEED_LEAD_IDS = [
  '00000000-0000-4000-8000-000000000001',
  '00000000-0000-4000-8000-000000000002',
  '00000000-0000-4000-8000-000000000003',
  '00000000-0000-4000-8000-000000000004',
  '00000000-0000-4000-8000-000000000005',
  '00000000-0000-4000-8000-000000000006',
  '00000000-0000-4000-8000-000000000007',
  '00000000-0000-4000-8000-000000000008',
  '00000000-0000-4000-8000-000000000009',
  '00000000-0000-4000-8000-00000000000a',
  '00000000-0000-4000-8000-00000000000b',
  '00000000-0000-4000-8000-00000000000c',
  '00000000-0000-4000-8000-00000000000d',
  '00000000-0000-4000-8000-00000000000e',
  '00000000-0000-4000-8000-00000000000f',
  '00000000-0000-4000-8000-000000000010',
  '00000000-0000-4000-8000-000000000011',
  '00000000-0000-4000-8000-000000000012',
] as const;

export const SEED_USERS = [
  {
    email: 'admin@nekofix.local',
    name: 'Administrador',
    role: UserRole.ADMIN,
    envPassword: 'SEED_ADMIN_PASSWORD',
    defaultPassword: 'Admin123!',
  },
  {
    email: 'cliente@nekofix.local',
    name: 'Cliente Demo',
    role: UserRole.CLIENT,
    envPassword: 'SEED_CLIENT_PASSWORD',
    defaultPassword: 'Cliente123!',
  },
] as const;

export const SEED_BRANDS = [
  { slug: 'apple', name: 'Apple', logo: 'https://logo.clearbit.com/apple.com' },
  {
    slug: 'samsung',
    name: 'Samsung',
    logo: 'https://logo.clearbit.com/samsung.com',
  },
  { slug: 'xiaomi', name: 'Xiaomi', logo: 'https://logo.clearbit.com/mi.com' },
  {
    slug: 'motorola',
    name: 'Motorola',
    logo: 'https://logo.clearbit.com/motorola.com',
  },
  { slug: 'huawei', name: 'Huawei', logo: 'https://logo.clearbit.com/huawei.com' },
  { slug: 'jbl', name: 'JBL', logo: 'https://logo.clearbit.com/jbl.com' },
  { slug: 'anker', name: 'Anker', logo: 'https://logo.clearbit.com/anker.com' },
  { slug: 'baseus', name: 'Baseus', logo: 'https://logo.clearbit.com/baseus.com' },
] as const;

export const SEED_CATEGORIES = [
  { slug: 'smartphones', name: 'Smartphones', icon: 'smartphone' },
  { slug: 'tablets', name: 'Tablets', icon: 'tablet' },
  { slug: 'smartwatch', name: 'Smartwatch', icon: 'watch' },
  { slug: 'audifonos', name: 'Audifonos', icon: 'headphones' },
  { slug: 'cargadores', name: 'Cargadores', icon: 'bolt' },
  { slug: 'fundas', name: 'Fundas', icon: 'shield' },
  { slug: 'pantallas', name: 'Pantallas', icon: 'display' },
  { slug: 'baterias', name: 'Baterias', icon: 'battery' },
  { slug: 'repuestos', name: 'Repuestos', icon: 'wrench' },
  { slug: 'accesorios', name: 'Accesorios', icon: 'cable' },
] as const;

export const SEED_PHONE_MODELS = [
  { slug: 'iphone-13', name: 'iPhone 13', brandSlug: 'apple' },
  { slug: 'iphone-14-pro', name: 'iPhone 14 Pro', brandSlug: 'apple' },
  {
    slug: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    brandSlug: 'apple',
  },
  { slug: 'galaxy-s23', name: 'Galaxy S23', brandSlug: 'samsung' },
  {
    slug: 'galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brandSlug: 'samsung',
  },
  { slug: 'galaxy-a55', name: 'Galaxy A55', brandSlug: 'samsung' },
  { slug: 'redmi-note-13', name: 'Redmi Note 13', brandSlug: 'xiaomi' },
  { slug: 'xiaomi-14', name: 'Xiaomi 14', brandSlug: 'xiaomi' },
  { slug: 'poco-x6', name: 'Poco X6', brandSlug: 'xiaomi' },
  { slug: 'edge-40', name: 'Edge 40', brandSlug: 'motorola' },
  { slug: 'moto-g84', name: 'Moto G84', brandSlug: 'motorola' },
  { slug: 'p60-pro', name: 'P60 Pro', brandSlug: 'huawei' },
  { slug: 'nova-11', name: 'Nova 11', brandSlug: 'huawei' },
] as const;

const img = (n: 2 | 3 | 4): 2 | 3 | 4 => n;

export const SEED_PRODUCTS: SeedProductDef[] = [
  {
    slug: 'nkfx-iphone-13-256-sierra',
    sku: 'NKFX-IP13-256-SIE',
    name: 'iPhone 13 256GB Sierra Blue',
    description:
      'Pantalla Super Retina XDR 6.1", chip A15 Bionic, gran autonomía. Unidad revisada con garantía NekoFix.',
    brandSlug: 'apple',
    categorySlug: 'smartphones',
    modelSlug: 'iphone-13',
    type: ProductType.USED,
    condition: ProductCondition.SEMINUEVO,
    price: '2999.00',
    comparePrice: '3499.00',
    stock: 14,
    minStock: 2,
    storage: '256 GB',
    color: 'Sierra Blue',
    batteryHealth: 91,
    grade: 'A',
    isFeatured: true,
    seoTitle: 'iPhone 13 256GB Sierra Blue seminuevo',
    seoDescription: 'iPhone 13 256 GB seminuevo con inspección técnica NekoFix.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-iphone-14-pro-512-purple',
    sku: 'NKFX-IP14P-512-PUR',
    name: 'iPhone 14 Pro 512GB Morado oscuro',
    description:
      'Dynamic Island, cámara ProRAW 48 MP, chip A16 Bionic. Rendimiento flagship para creadores.',
    brandSlug: 'apple',
    categorySlug: 'smartphones',
    modelSlug: 'iphone-14-pro',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '5299.00',
    comparePrice: '5799.00',
    stock: 6,
    minStock: 1,
    storage: '512 GB',
    color: 'Morado oscuro',
    isFeatured: true,
    seoTitle: 'iPhone 14 Pro 512GB nuevo',
    seoDescription: 'iPhone 14 Pro nuevo sellado con factura.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-iphone-15-pro-max-256-natural',
    sku: 'NKFX-IP15PM-256-NAT',
    name: 'iPhone 15 Pro Max 256GB Titanio natural',
    description:
      'Chip A17 Pro, USB-C, zoom tetraprisma 5x. La experiencia iPhone más completa.',
    brandSlug: 'apple',
    categorySlug: 'smartphones',
    modelSlug: 'iphone-15-pro-max',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '6499.00',
    stock: 4,
    minStock: 1,
    storage: '256 GB',
    color: 'Titanio natural',
    isFeatured: true,
    seoTitle: 'iPhone 15 Pro Max 256GB',
    seoDescription: 'iPhone 15 Pro Max nuevo distribuidor autorizado.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-samsung-s24-ultra-512-black',
    sku: 'NKFX-S24U-512-BLK',
    name: 'Samsung Galaxy S24 Ultra 512GB Titanium Black',
    description:
      'Snapdragon 8 Gen 3, S Pen integrado, pantalla Dynamic AMOLED 2X 120 Hz, IA Galaxy AI.',
    brandSlug: 'samsung',
    categorySlug: 'smartphones',
    modelSlug: 'galaxy-s24-ultra',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '5899.00',
    comparePrice: '6299.00',
    stock: 5,
    minStock: 1,
    storage: '512 GB',
    color: 'Titanium Black',
    isFeatured: true,
    seoTitle: 'Galaxy S24 Ultra 512GB',
    seoDescription: 'Samsung S24 Ultra nuevo con S Pen.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-samsung-s23-256-green',
    sku: 'NKFX-S23-256-GRN',
    name: 'Samsung Galaxy S23 256GB Green',
    description:
      'Compacto flagship con Nightography, 120 Hz y resistencia IP68. Excelente ergonomía.',
    brandSlug: 'samsung',
    categorySlug: 'smartphones',
    modelSlug: 'galaxy-s23',
    type: ProductType.USED,
    condition: ProductCondition.REFURBISHED,
    price: '2799.00',
    stock: 9,
    minStock: 2,
    storage: '256 GB',
    color: 'Green',
    batteryHealth: 89,
    grade: 'A',
    isFeatured: false,
    seoTitle: 'Galaxy S23 256GB reacondicionado',
    seoDescription: 'S23 reacondicionado con batería certificada.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-samsung-a55-128-aw',
    sku: 'NKFX-A55-128-AW',
    name: 'Samsung Galaxy A55 128GB Awesome Navy',
    description:
      'Pantalla Super AMOLED 120 Hz, cámara triple 50 MP, actualizaciones prolongadas.',
    brandSlug: 'samsung',
    categorySlug: 'smartphones',
    modelSlug: 'galaxy-a55',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '1399.00',
    stock: 24,
    minStock: 4,
    storage: '128 GB',
    color: 'Awesome Navy',
    isFeatured: false,
    seoTitle: 'Galaxy A55 128GB',
    seoDescription: 'Samsung A55 gama media premium.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-xiaomi-14-512-black',
    sku: 'NKFX-XM14-512-BLK',
    name: 'Xiaomi 14 512GB Negro',
    description:
      'Leica Summilux, Snapdragon 8 Gen 3, carga 90W. Fotografía flagship en formato compacto.',
    brandSlug: 'xiaomi',
    categorySlug: 'smartphones',
    modelSlug: 'xiaomi-14',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '3299.00',
    stock: 8,
    minStock: 2,
    storage: '512 GB',
    color: 'Negro',
    isFeatured: true,
    seoTitle: 'Xiaomi 14 512GB',
    seoDescription: 'Xiaomi 14 con cámaras Leica.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-redmi-note-13-256-mint',
    sku: 'NKFX-RN13-256-MNT',
    name: 'Xiaomi Redmi Note 13 256GB Mint Green',
    description:
      'AMOLED 120 Hz, cámara 108 MP, carga 33W. Relación calidad-precio imbatible.',
    brandSlug: 'xiaomi',
    categorySlug: 'smartphones',
    modelSlug: 'redmi-note-13',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '999.00',
    stock: 32,
    minStock: 6,
    storage: '256 GB',
    color: 'Mint Green',
    isFeatured: true,
    seoTitle: 'Redmi Note 13 256GB',
    seoDescription: 'Redmi Note 13 con NFC y IR.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-poco-x6-512-negro',
    sku: 'NKFX-PX6-512-BLK',
    name: 'Poco X6 512GB Negro',
    description:
      'Snapdragon 7s Gen 2, pantalla 1.5K 120 Hz, batería 5100 mAh.',
    brandSlug: 'xiaomi',
    categorySlug: 'smartphones',
    modelSlug: 'poco-x6',
    type: ProductType.USED,
    condition: ProductCondition.SEMINUEVO,
    price: '1199.00',
    comparePrice: '1399.00',
    stock: 11,
    minStock: 2,
    storage: '512 GB',
    color: 'Negro',
    batteryHealth: 93,
    grade: 'A',
    isFeatured: false,
    seoTitle: 'Poco X6 512GB seminuevo',
    seoDescription: 'Poco X6 en excelente estado.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-moto-edge-40-256-vapor',
    sku: 'NKFX-E40-256-VAP',
    name: 'Motorola Edge 40 256GB Vapor',
    description:
      'Pantalla pOLED curva 144 Hz, carga 68W, experiencia Android puro.',
    brandSlug: 'motorola',
    categorySlug: 'smartphones',
    modelSlug: 'edge-40',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '1899.00',
    stock: 10,
    minStock: 2,
    storage: '256 GB',
    color: 'Vapor',
    isFeatured: false,
    seoTitle: 'Motorola Edge 40 256GB',
    seoDescription: 'Edge 40 con Dolby Atmos.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-moto-g84-256-azul',
    sku: 'NKFX-G84-256-BLU',
    name: 'Motorola Moto G84 256GB Azul',
    description:
      'OLED 120 Hz, altavoces Dolby, cámara 50 MP con OIS.',
    brandSlug: 'motorola',
    categorySlug: 'smartphones',
    modelSlug: 'moto-g84',
    type: ProductType.USED,
    condition: ProductCondition.SEMINUEVO,
    price: '949.00',
    stock: 15,
    minStock: 3,
    storage: '256 GB',
    color: 'Azul',
    batteryHealth: 88,
    grade: 'B',
    isFeatured: false,
    seoTitle: 'Moto G84 256GB',
    seoDescription: 'Moto G84 seminuevo revisado.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-huawei-p60-pro-256-blanco',
    sku: 'NKFX-P60-256-WHT',
    name: 'Huawei P60 Pro 256GB Rococo Pearl',
    description:
      'Cámara RYYB ultravisión, telemacro, carga 88W. Diseño premium único.',
    brandSlug: 'huawei',
    categorySlug: 'smartphones',
    modelSlug: 'p60-pro',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '4299.00',
    stock: 3,
    minStock: 1,
    storage: '256 GB',
    color: 'Rococo Pearl',
    isFeatured: true,
    seoTitle: 'Huawei P60 Pro 256GB',
    seoDescription: 'Huawei P60 Pro con cámara XMAGE.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-huawei-nova-11-128-verde',
    sku: 'NKFX-NV11-128-GRN',
    name: 'Huawei Nova 11 128GB Verde',
    description:
      'Pantalla OLED 120 Hz, cámara selfie 60 MP, carga 66W.',
    brandSlug: 'huawei',
    categorySlug: 'smartphones',
    modelSlug: 'nova-11',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '1599.00',
    stock: 12,
    minStock: 2,
    storage: '128 GB',
    color: 'Verde',
    isFeatured: false,
    seoTitle: 'Huawei Nova 11 128GB',
    seoDescription: 'Nova 11 para fotografía selfie.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-iphone-12-64-reparado',
    sku: 'NKFX-IP12-64-REP',
    name: 'iPhone 12 64GB Negro (reparado)',
    description:
      'Unidad con pantalla y batería reemplazadas en taller autorizado. Funcionalidad verificada.',
    brandSlug: 'apple',
    categorySlug: 'smartphones',
    type: ProductType.USED,
    condition: ProductCondition.REPAIRED,
    price: '1399.00',
    stock: 5,
    minStock: 1,
    storage: '64 GB',
    color: 'Negro',
    batteryHealth: 100,
    grade: 'B',
    isFeatured: false,
    seoTitle: 'iPhone 12 64GB reparado',
    seoDescription: 'iPhone 12 con repuestos certificados.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-ipad-11-128-wifi-gris',
    sku: 'NKFX-IPD11-128-GRY',
    name: 'iPad 11" 128GB WiFi Gris espacial',
    description:
      'Chip A16, pantalla Liquid Retina, compatible Apple Pencil USB-C.',
    brandSlug: 'apple',
    categorySlug: 'tablets',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '2199.00',
    stock: 7,
    minStock: 1,
    storage: '128 GB',
    color: 'Gris espacial',
    isFeatured: true,
    seoTitle: 'iPad 11 128GB WiFi',
    seoDescription: 'iPad 11 pulgadas nueva generación.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-tab-s9-256-wifi-graphite',
    sku: 'NKFX-TABS9-256-GRF',
    name: 'Samsung Galaxy Tab S9 256GB WiFi Graphite',
    description:
      'Dynamic AMOLED 2X, S Pen incluido, IP68. Productividad y entretenimiento.',
    brandSlug: 'samsung',
    categorySlug: 'tablets',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '3199.00',
    stock: 4,
    minStock: 1,
    storage: '256 GB',
    color: 'Graphite',
    isFeatured: true,
    seoTitle: 'Galaxy Tab S9 256GB',
    seoDescription: 'Tablet Tab S9 con S Pen.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-redmi-pad-se-128-gris',
    sku: 'NKFX-RPAD-128-GRY',
    name: 'Redmi Pad SE 128GB Gris',
    description:
      'Pantalla 11" 90 Hz, cuatro altavoces, batería 8000 mAh.',
    brandSlug: 'xiaomi',
    categorySlug: 'tablets',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '749.00',
    stock: 18,
    minStock: 3,
    storage: '128 GB',
    color: 'Gris',
    isFeatured: false,
    seoTitle: 'Redmi Pad SE 128GB',
    seoDescription: 'Tablet económica Redmi Pad SE.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-apple-watch-s9-45-midnight',
    sku: 'NKFX-AWS9-45-MID',
    name: 'Apple Watch Series 9 GPS 45mm Medianoche',
    description:
      'Chip S9, doble toque, brillo 2000 nits. Salud y fitness en tu muñeca.',
    brandSlug: 'apple',
    categorySlug: 'smartwatch',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '1899.00',
    comparePrice: '1999.00',
    stock: 9,
    minStock: 2,
    color: 'Medianoche',
    isFeatured: true,
    seoTitle: 'Apple Watch Series 9 45mm',
    seoDescription: 'Apple Watch S9 GPS 45 mm.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-galaxy-watch6-44-graphite',
    sku: 'NKFX-GW6-44-GRF',
    name: 'Samsung Galaxy Watch6 44mm Graphite',
    description:
      'Sensor de composición corporal, Wear OS, pantalla Super AMOLED.',
    brandSlug: 'samsung',
    categorySlug: 'smartwatch',
    type: ProductType.NEW,
    condition: ProductCondition.NEW,
    price: '1099.00',
    stock: 11,
    minStock: 2,
    color: 'Graphite',
    isFeatured: true,
    seoTitle: 'Galaxy Watch6 44mm',
    seoDescription: 'Samsung Galaxy Watch6 Bluetooth.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-huawei-watch-gt4-46-negro',
    sku: 'NKFX-WGT4-46-BLK',
    name: 'Huawei Watch GT 4 46mm Negro',
    description:
      'Hasta 14 días de batería, rutas de golf, monitoreo avanzado del sueño.',
    brandSlug: 'huawei',
    categorySlug: 'smartwatch',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '899.00',
    stock: 6,
    minStock: 1,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Huawei Watch GT 4 46mm',
    seoDescription: 'Smartwatch Huawei GT 4.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-jbl-tune-520bt-negro',
    sku: 'NKFX-JBL-520BT-BLK',
    name: 'Audífonos JBL Tune 520BT Negro',
    description:
      'Bluetooth multipunto, batería hasta 57 h, sonido JBL Pure Bass.',
    brandSlug: 'jbl',
    categorySlug: 'audifonos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '199.00',
    comparePrice: '249.00',
    stock: 45,
    minStock: 8,
    color: 'Negro',
    isFeatured: true,
    seoTitle: 'JBL Tune 520BT',
    seoDescription: 'Auriculares on-ear Bluetooth JBL.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-jbl-tune-760nc-azul',
    sku: 'NKFX-JBL-760NC-BLU',
    name: 'JBL Tune 760NC Azul',
    description:
      'Cancelación activa de ruido, hasta 35 h, plegables para viaje.',
    brandSlug: 'jbl',
    categorySlug: 'audifonos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '299.00',
    stock: 28,
    minStock: 5,
    color: 'Azul',
    isFeatured: false,
    seoTitle: 'JBL Tune 760NC',
    seoDescription: 'Over-ear JBL con ANC.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-jbl-go-4-negro',
    sku: 'NKFX-JBL-GO4-BLK',
    name: 'JBL Go 4 Negro',
    description:
      'Parlante Bluetooth IP67, diseño compacto, hasta 7 h de reproducción.',
    brandSlug: 'jbl',
    categorySlug: 'audifonos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '149.00',
    stock: 52,
    minStock: 10,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'JBL Go 4',
    seoDescription: 'Parlante portátil JBL Go 4.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-huawei-freebuds-5i-blanco',
    sku: 'NKFX-FB5I-WHT',
    name: 'Huawei FreeBuds 5i Blanco',
    description:
      'ANC híbrido, batería hasta 28 h con estuche, bajos potentes.',
    brandSlug: 'huawei',
    categorySlug: 'audifonos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '279.00',
    stock: 20,
    minStock: 4,
    color: 'Blanco',
    isFeatured: false,
    seoTitle: 'Huawei FreeBuds 5i',
    seoDescription: 'TWS Huawei con cancelación de ruido.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-apple-magsafe-20w',
    sku: 'NKFX-AC-MS20W',
    name: 'Cargador Apple MagSafe 20W USB-C',
    description:
      'Carga rápida compatible con iPhone y accesorios MagSafe. Compacto y seguro.',
    brandSlug: 'apple',
    categorySlug: 'cargadores',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '129.00',
    stock: 60,
    minStock: 12,
    color: 'Blanco',
    isFeatured: true,
    seoTitle: 'Cargador MagSafe 20W Apple',
    seoDescription: 'Adaptador USB-C 20W original Apple.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-anker-gan-65w-3p',
    sku: 'NKFX-AK-65W-GAN',
    name: 'Cargador Anker GaN 65W 3 puertos',
    description:
      'Tecnología GaN, dos USB-C y un USB-A. Ideal para laptop y teléfono.',
    brandSlug: 'anker',
    categorySlug: 'cargadores',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '219.00',
    comparePrice: '259.00',
    stock: 40,
    minStock: 8,
    color: 'Negro',
    isFeatured: true,
    seoTitle: 'Cargador Anker GaN 65W',
    seoDescription: 'Cargador multipuerto Anker 65W.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-baseus-100w-cable-2m',
    sku: 'NKFX-BS-C100-2M',
    name: 'Cable Baseus USB-C 100W 2m',
    description:
      'Cable con chip E-Marker, soporta carga rápida para laptops y smartphones.',
    brandSlug: 'baseus',
    categorySlug: 'cargadores',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '69.00',
    stock: 85,
    minStock: 15,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Cable USB-C Baseus 100W',
    seoDescription: 'Cable USB-C 100W 2 metros.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-motorola-turbo-30w',
    sku: 'NKFX-MOT-TUR-30W',
    name: 'Cargador Motorola TurboPower 30W',
    description:
      'Carga rápida para familia Moto. Incluye cable USB-C.',
    brandSlug: 'motorola',
    categorySlug: 'cargadores',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '89.00',
    stock: 35,
    minStock: 6,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'TurboPower 30W Motorola',
    seoDescription: 'Cargador rápido Motorola 30W.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-xiaomi-67w-charger',
    sku: 'NKFX-XM-67W-CHG',
    name: 'Cargador Xiaomi 67W con cable',
    description:
      'Compatible con gama Xiaomi y Redmi con carga turbo. Incluye cable USB-C.',
    brandSlug: 'xiaomi',
    categorySlug: 'cargadores',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '99.00',
    stock: 42,
    minStock: 8,
    color: 'Blanco',
    isFeatured: false,
    seoTitle: 'Cargador Xiaomi 67W',
    seoDescription: 'Cargador 67W con cable incluido.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-funda-s24-ultra-clear',
    sku: 'NKFX-FD-S24U-CLR',
    name: 'Funda transparente Galaxy S24 Ultra',
    description:
      'TPU antiamarilleo, esquinas reforzadas, compatible carga inalámbrica.',
    brandSlug: 'samsung',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '79.00',
    stock: 55,
    minStock: 10,
    color: 'Transparente',
    isFeatured: false,
    seoTitle: 'Funda Galaxy S24 Ultra',
    seoDescription: 'Funda transparente S24 Ultra.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-funda-iphone-15-pro-silicona',
    sku: 'NKFX-FD-IP15P-SIL',
    name: 'Funda silicona iPhone 15 Pro Azul',
    description:
      'Interior microfibra, compatible MagSafe, tacto suave.',
    brandSlug: 'apple',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '149.00',
    stock: 38,
    minStock: 8,
    color: 'Azul',
    isFeatured: true,
    seoTitle: 'Funda silicona iPhone 15 Pro',
    seoDescription: 'Funda MagSafe iPhone 15 Pro.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-funda-p60-pro-wallet',
    sku: 'NKFX-FD-P60-WAL',
    name: 'Funda tipo cartera Huawei P60 Pro',
    description:
      'Cuero sintético, ranuras para tarjetas, función soporte.',
    brandSlug: 'huawei',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '99.00',
    stock: 22,
    minStock: 4,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Funda cartera P60 Pro',
    seoDescription: 'Funda wallet Huawei P60 Pro.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-funda-moto-g84-rugged',
    sku: 'NKFX-FD-G84-RUG',
    name: 'Funda antigolpes Moto G84',
    description:
      'Bordes reforzados, agarre texturizado, recortes precisos.',
    brandSlug: 'motorola',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '59.00',
    stock: 30,
    minStock: 6,
    color: 'Gris',
    isFeatured: false,
    seoTitle: 'Funda antigolpes Moto G84',
    seoDescription: 'Funda resistente Moto G84.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-funda-redmi-note-13-flip',
    sku: 'NKFX-FD-RN13-FLP',
    name: 'Funda libro Redmi Note 13',
    description:
      'Cierre magnético, función atril para video, protección frontal.',
    brandSlug: 'xiaomi',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '49.00',
    stock: 48,
    minStock: 10,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Funda libro Redmi Note 13',
    seoDescription: 'Funda tipo flip Redmi Note 13.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-funda-ipad-11-smart',
    sku: 'NKFX-FD-IPD11-SMT',
    name: 'Funda Smart Folio iPad 11"',
    description:
      'Delgada, despierta al abrir, soporte para escritura y dibujo.',
    brandSlug: 'apple',
    categorySlug: 'fundas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '329.00',
    stock: 12,
    minStock: 2,
    color: 'Azul marino',
    isFeatured: false,
    seoTitle: 'Smart Folio iPad 11',
    seoDescription: 'Funda oficial estilo Smart Folio.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-pantalla-iphone-14-pro-oled',
    sku: 'NKFX-SCR-IP14P-OLED',
    name: 'Pantalla iPhone 14 Pro OLED (repuesto)',
    description:
      'Módulo OLED compatible con Dynamic Island, incluye herramientas básicas. Instalación en taller.',
    brandSlug: 'apple',
    categorySlug: 'pantallas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '899.00',
    stock: 6,
    minStock: 1,
    color: 'Negro',
    isFeatured: true,
    seoTitle: 'Pantalla OLED iPhone 14 Pro',
    seoDescription: 'Repuesto pantalla iPhone 14 Pro.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-pantalla-s23-g5-oled',
    sku: 'NKFX-SCR-S23-OLED',
    name: 'Pantalla Samsung S23 OLED servicio',
    description:
      'Módulo original service pack, calibración de color. Recomendado instalación profesional.',
    brandSlug: 'samsung',
    categorySlug: 'pantallas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '749.00',
    stock: 4,
    minStock: 1,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Pantalla OLED Galaxy S23',
    seoDescription: 'Repuesto pantalla S23.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-pantalla-redmi-note-13-lcd',
    sku: 'NKFX-SCR-RN13-LCD',
    name: 'Pantalla LCD Redmi Note 13',
    description:
      'Panel LCD IPS con marco, compatible táctil y brillo original.',
    brandSlug: 'xiaomi',
    categorySlug: 'pantallas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '249.00',
    stock: 9,
    minStock: 2,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Pantalla Redmi Note 13',
    seoDescription: 'LCD Redmi Note 13 repuesto.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-pantalla-moto-g84',
    sku: 'NKFX-SCR-G84-LCD',
    name: 'Pantalla Moto G84 LCD completa',
    description:
      'Módulo LCD + táctil ensamblado, listo para montaje.',
    brandSlug: 'motorola',
    categorySlug: 'pantallas',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '199.00',
    stock: 7,
    minStock: 2,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Pantalla Moto G84',
    seoDescription: 'Repuesto pantalla Moto G84.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-bateria-redmi-note-13-oem',
    sku: 'NKFX-BAT-RN13-OEM',
    name: 'Batería Xiaomi Redmi Note 13 OEM',
    description:
      'Capacidad nominal 5000 mAh, ciclos certificados. Incluye kit adhesivos.',
    brandSlug: 'xiaomi',
    categorySlug: 'baterias',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '89.00',
    stock: 25,
    minStock: 5,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Batería Redmi Note 13',
    seoDescription: 'Batería OEM Redmi Note 13.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-bateria-iphone-13-original',
    sku: 'NKFX-BAT-IP13-ORG',
    name: 'Batería iPhone 13 servicio original',
    description:
      'Pieza de servicio Apple, herramientas y calibración recomendadas en taller.',
    brandSlug: 'apple',
    categorySlug: 'baterias',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '299.00',
    stock: 8,
    minStock: 2,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Batería iPhone 13',
    seoDescription: 'Batería servicio iPhone 13.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-bateria-s24-ultra-oem',
    sku: 'NKFX-BAT-S24U-OEM',
    name: 'Batería Samsung S24 Ultra OEM',
    description:
      'Ion-litio 5000 mAh, sellada anti-hinchazón. Instalación con precisión.',
    brandSlug: 'samsung',
    categorySlug: 'baterias',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '199.00',
    stock: 10,
    minStock: 2,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Batería Galaxy S24 Ultra',
    seoDescription: 'Batería OEM S24 Ultra.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-repuesto-ip14p-camara-trasera',
    sku: 'NKFX-REP-IP14P-CAM',
    name: 'Módulo cámara trasera iPhone 14 Pro',
    description:
      'Conjunto triple cámara con estabilización. Repuesto para reparación avanzada.',
    brandSlug: 'apple',
    categorySlug: 'repuestos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '1299.00',
    stock: 2,
    minStock: 1,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Cámara trasera iPhone 14 Pro',
    seoDescription: 'Repuesto cámara iPhone 14 Pro.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-repuesto-s23-puerto-carga',
    sku: 'NKFX-REP-S23-USB',
    name: 'Puerto de carga Samsung S23',
    description:
      'Flex USB-C con micrófono secundario, compatible con S23 estándar.',
    brandSlug: 'samsung',
    categorySlug: 'repuestos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '149.00',
    stock: 11,
    minStock: 2,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Puerto carga Galaxy S23',
    seoDescription: 'Flex USB-C S23.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-repuesto-poco-x6-altavoz',
    sku: 'NKFX-REP-PX6-SP',
    name: 'Altavoz inferior Poco X6',
    description:
      'Módulo buzzer con rejilla, sonido estéreo restaurado.',
    brandSlug: 'xiaomi',
    categorySlug: 'repuestos',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '45.00',
    stock: 18,
    minStock: 4,
    color: 'Negro',
    isFeatured: false,
    seoTitle: 'Altavoz Poco X6',
    seoDescription: 'Repuesto altavoz Poco X6.',
    imageCount: img(2),
  },
  {
    slug: 'nkfx-accesorio-baseus-hub-5in1',
    sku: 'NKFX-ACC-BS-HUB5',
    name: 'Hub USB-C Baseus 5 en 1',
    description:
      'HDMI 4K, 2× USB-A, lector SD, PD 100W passthrough.',
    brandSlug: 'baseus',
    categorySlug: 'accesorios',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '189.00',
    stock: 20,
    minStock: 4,
    color: 'Gris',
    isFeatured: true,
    seoTitle: 'Hub USB-C Baseus 5 en 1',
    seoDescription: 'Hub multipuerto para laptop.',
    imageCount: img(4),
  },
  {
    slug: 'nkfx-accesorio-anker-powerbank-20k',
    sku: 'NKFX-ACC-AK-PB20',
    name: 'Power Bank Anker 20000 mAh 22.5W',
    description:
      'Dos salidas USB-A y USB-C, pantalla LED, carga simultánea.',
    brandSlug: 'anker',
    categorySlug: 'accesorios',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '179.00',
    comparePrice: '219.00',
    stock: 33,
    minStock: 6,
    color: 'Negro',
    isFeatured: true,
    seoTitle: 'Power Bank Anker 20000',
    seoDescription: 'Batería portátil Anker 20000 mAh.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-accesorio-jbl-clip5',
    sku: 'NKFX-ACC-JBL-C5',
    name: 'JBL Clip 5 Azul',
    description:
      'Parlante Bluetooth con mosquetón, IP67, hasta 12 h.',
    brandSlug: 'jbl',
    categorySlug: 'accesorios',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '219.00',
    stock: 16,
    minStock: 3,
    color: 'Azul',
    isFeatured: false,
    seoTitle: 'JBL Clip 5',
    seoDescription: 'Parlante portátil JBL Clip 5.',
    imageCount: img(3),
  },
  {
    slug: 'nkfx-accesorio-huawei-nfc-tag',
    sku: 'NKFX-ACC-HW-NFC',
    name: 'Etiquetas NFC Huawei (pack 2)',
    description:
      'Automatiza escenas en smartphone Huawei con un toque.',
    brandSlug: 'huawei',
    categorySlug: 'accesorios',
    type: ProductType.ACCESSORY,
    condition: ProductCondition.NEW,
    price: '39.00',
    stock: 40,
    minStock: 8,
    color: 'Blanco',
    isFeatured: false,
    seoTitle: 'Etiquetas NFC Huawei',
    seoDescription: 'Pack etiquetas NFC Huawei.',
    imageCount: img(2),
  },
];

export const SEED_LEADS: SeedLeadDef[] = [
  {
    id: SEED_LEAD_IDS[0],
    phone: '+51987654321',
    daysAgo: 0,
    hoursOffset: 0,
    items: [
      { slug: 'nkfx-iphone-15-pro-max-256-natural', qty: 1, unitPrice: '6499.00' },
      { slug: 'nkfx-apple-magsafe-20w', qty: 1, unitPrice: '129.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[1],
    phone: '+51912345678',
    daysAgo: 0,
    hoursOffset: 6,
    items: [{ slug: 'nkfx-samsung-s24-ultra-512-black', qty: 1, unitPrice: '5899.00' }],
  },
  {
    id: SEED_LEAD_IDS[2],
    phone: '+51923456789',
    daysAgo: 1,
    items: [
      { slug: 'nkfx-jbl-tune-520bt-negro', qty: 1, unitPrice: '199.00' },
      { slug: 'nkfx-jbl-go-4-negro', qty: 1, unitPrice: '149.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[3],
    phone: '+51934567890',
    daysAgo: 2,
    items: [{ slug: 'nkfx-redmi-note-13-256-mint', qty: 2, unitPrice: '999.00' }],
  },
  {
    id: SEED_LEAD_IDS[4],
    phone: '+51945678901',
    daysAgo: 3,
    items: [
      { slug: 'nkfx-ipad-11-128-wifi-gris', qty: 1, unitPrice: '2199.00' },
      { slug: 'nkfx-funda-ipad-11-smart', qty: 1, unitPrice: '329.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[5],
    phone: '+51956789012',
    daysAgo: 5,
    items: [{ slug: 'nkfx-galaxy-watch6-44-graphite', qty: 1, unitPrice: '1099.00' }],
  },
  {
    id: SEED_LEAD_IDS[6],
    phone: '+51967890123',
    daysAgo: 7,
    items: [
      { slug: 'nkfx-anker-gan-65w-3p', qty: 1, unitPrice: '219.00' },
      { slug: 'nkfx-baseus-100w-cable-2m', qty: 2, unitPrice: '69.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[7],
    phone: '+51978901234',
    daysAgo: 0,
    hoursOffset: 14,
    items: [{ slug: 'nkfx-poco-x6-512-negro', qty: 1, unitPrice: '1199.00' }],
  },
  {
    id: SEED_LEAD_IDS[8],
    phone: '+51989012345',
    daysAgo: 10,
    items: [{ slug: 'nkfx-moto-edge-40-256-vapor', qty: 1, unitPrice: '1899.00' }],
  },
  {
    id: SEED_LEAD_IDS[9],
    phone: '+51990123456',
    daysAgo: 14,
    items: [{ slug: 'nkfx-iphone-14-pro-512-purple', qty: 1, unitPrice: '5299.00' }],
  },
  {
    id: SEED_LEAD_IDS[10],
    phone: '+51901234567',
    daysAgo: 21,
    items: [
      { slug: 'nkfx-accesorio-baseus-hub-5in1', qty: 1, unitPrice: '189.00' },
      { slug: 'nkfx-funda-s24-ultra-clear', qty: 1, unitPrice: '79.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[11],
    phone: '+51912345098',
    daysAgo: 28,
    items: [{ slug: 'nkfx-tab-s9-256-wifi-graphite', qty: 1, unitPrice: '3199.00' }],
  },
  {
    id: SEED_LEAD_IDS[12],
    phone: '+51923456109',
    daysAgo: 30,
    items: [
      { slug: 'nkfx-apple-watch-s9-45-midnight', qty: 1, unitPrice: '1899.00' },
      { slug: 'nkfx-funda-iphone-15-pro-silicona', qty: 1, unitPrice: '149.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[13],
    phone: '+51934567210',
    daysAgo: 4,
    items: [{ slug: 'nkfx-huawei-freebuds-5i-blanco', qty: 1, unitPrice: '279.00' }],
  },
  {
    id: SEED_LEAD_IDS[14],
    phone: '+51945678321',
    daysAgo: 6,
    items: [
      { slug: 'nkfx-iphone-13-256-sierra', qty: 1, unitPrice: '2999.00' },
      { slug: 'nkfx-baseus-100w-cable-2m', qty: 1, unitPrice: '69.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[15],
    phone: '+51956789432',
    daysAgo: 8,
    items: [{ slug: 'nkfx-xiaomi-14-512-black', qty: 1, unitPrice: '3299.00' }],
  },
  {
    id: SEED_LEAD_IDS[16],
    phone: '+51967890543',
    daysAgo: 12,
    items: [
      { slug: 'nkfx-pantalla-iphone-14-pro-oled', qty: 1, unitPrice: '899.00' },
    ],
  },
  {
    id: SEED_LEAD_IDS[17],
    phone: '+51978901654',
    daysAgo: 15,
    items: [
      { slug: 'nkfx-accesorio-anker-powerbank-20k', qty: 1, unitPrice: '179.00' },
      { slug: 'nkfx-motorola-turbo-30w', qty: 1, unitPrice: '89.00' },
    ],
  },
];
